### ISSUE TITLE
Package as library and put on maven?

### ISSUE THREAD

**Issue by chakrit** [Innovattic/Android-Font-Library#1]
Is it possible to package and put this library so we can import it easily when using maven/gradle ?

**Comment by jfresen** [comment]
It has taken quite a while, but I have finally taken up this task. A first version is in the process of being deployed as we speak. When it is done, I will update the readme with the new instructions for gradle.

**Comment by jfresen** [comment]
It has been released, you can now simply add it as a gradle dependency with `com.innovattic:fontlib:4.0.0`
