### ISSUE TITLE
Android Studio designer error

### ISSUE THREAD

**Issue by HaukeRa** [Innovattic/Android-Font-Library#9]
The Android Studio layout designer always throws an exception when trying to render the views.
The exception is:

    java.lang.ClassFormatError: Code attribute in native or abstract methods in class file com/innovattic/font/TypefaceManager$DrawCallback

This is a struggle when working with ConstraintLayouts since the error pops up every time a view property is changed. Is there something to do about this?

**Comment by jfresen** [comment]
Hi,

The TypefaceManager defines an interface, DrawCallback, which is used to expose a view's super.onDraw method, which is a protected method and therefor not normally accessible to the TypefaceManager. This interface defines a single method, onDraw, which a font aware view can implement by calling its protected super.onDraw method. I named the interface's method the same as the view's method, so it had a nice symmetry, but apparently the ClassLoader thinks differently. I don't know why that is a problem, but changing the method name to something else solves it. I'll make a version 5.1.0, at the latest this weekend.

Thanks for reporting this issue!

**Comment by jfresen** [comment]
Version 5.1.0 released with the fix
